const $=id=>document.getElementById(id);
let authChecked=false,authLogged=false;
function updateConfigNotice(){$('configNotice').hidden=!authChecked||authLogged;}
let job=null,mode='processed',filter='all',selected=null,context=false,compare=false,warping=false,points=[],binding=false,dragStart=null,poll=null,dirty=false,busy=false,pendingFile=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,4000)}
async function api(path,options={}){const r=await fetch(path,options);if(!r.ok){let e;try{e=await r.json()}catch{e={detail:r.statusText}}throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r.json()}
async function run(fn){if(busy)return;busy=true;try{await fn()}catch(e){toast(e.message)}finally{busy=false;controls();guidance()}}
const body=obj=>({headers:{'Content-Type':'application/json'},body:JSON.stringify(obj)});
const normalizeText=s=>String(s||'').replace(/\s+/g,'');
function mismatch(c){return c.candidate_text!=null&&normalizeText(c.candidate_text)!==normalizeText(c.text)}
function score(c){return c.candidate_score??c.score??null}
function color(c){if(c.confirmed)return 'green';if(mismatch(c)||score(c)!==null&&score(c)<.95||c.assessment_source&&c.text.trim()&&c.candidate_text==null)return 'red';if(!c.text.trim()&&score(c)===null)return 'gray';return 'yellow'}
function scoreLabel(c){const v=score(c);return v===null?'未评分':`${(v*100).toFixed(1)} 分${mismatch(c)?' · 不一致':''}`}
function cellDetails(c){return `第 ${c.row} 行，第 ${c.col} 列 · ${c.candidate_score!=null?'本地复核候选':c.score!=null?'服务返回分数':'无分数'} ${scoreLabel(c)} · ${c.confirmed?'已确认':'待确认'}`}
function matchesFilter(c,f=filter){return !!c&&(f==='all'||f==='gray'&&!c.text.trim()||f==='red'&&color(c)==='red'||f==='yellow'&&color(c)==='yellow')}
function filtered(){return (job?.cells||[]).filter(c=>matchesFilter(c)).sort((a,b)=>a.row-b.row||a.col-b.col)}
function filterControls(){for(const f of ['red','yellow','gray','all']){for(const prefix of ['','viewer','proof']){const id=prefix?prefix+f[0].toUpperCase()+f.slice(1):f;const el=$(id);if(el){el.classList.toggle('active',filter===f);el.setAttribute('aria-pressed',String(filter===f))}}}if($('viewerFilterInfo'))$('viewerFilterInfo').textContent=filter==='all'?'显示全部格子':`已筛选 ${filtered().length} 格；再次点击同色按钮取消筛选`;}
function controls(){const has=!!job,working=job?.status==='recognizing';$('recognize').disabled=busy||!has||working||!!job?.cells.length;$('uploadRecognize').disabled=busy||working;$('startReview').disabled=busy||!job?.cells.length||working;$('assess').disabled=busy||working||!job?.cells.length||job?.provider!=='camscanner';$('upload').disabled=busy||working;$('save').disabled=busy||!job?.cells.length||working;$('exportDraft').disabled=busy||!job?.cells.length||working;$('export').disabled=busy||!job?.cells.length||working;$('export').title=working?'图片正在处理中，完成后可直接导出':!job?.cells.length?'识别出表格后即可导出，无需校对':'无需校对，自动保存已有修改并导出全部格子';$('proofExport').disabled=$('export').disabled;$('viewerExport').disabled=$('export').disabled;$('warp').disabled=busy||!has||working||!!job?.cells.length;$('exportName').disabled=busy||working;}
let configurationReady=false;try{configurationReady=localStorage.getItem('scanTableConfigured')==='true'}catch{}
function openConfiguration(){if(!$('settingsDialog').open)$('settingsDialog').showModal();refreshAuth();}
$('openConfig').onclick=openConfiguration;$('noticeConfig').onclick=openConfiguration;$('closeConfig').onclick=()=>$('settingsDialog').close();
$('saveConfig').onclick=()=>{saveSettings();configurationReady=true;try{localStorage.setItem('scanTableConfigured','true')}catch{}$('settingsDialog').close();guidance();toast('配置已保存，可以选择图片上传识别')};
const DEFAULT_SETTINGS={geometry:true,enhancement:'natural',provider:'camscanner',cloud:true};
function saveSettings(){try{localStorage.setItem('scanTableSettings',JSON.stringify({geometry:$('geometry').checked,enhancement:$('enhancement').value,provider:$('provider').value,cloud:$('cloud').checked}))}catch{}}
function restoreSettings(){let saved={};try{saved=JSON.parse(localStorage.getItem('scanTableSettings')||'{}')||{}}catch{}for(const key of ['geometry','cloud'])$(key).checked=typeof saved[key]==='boolean'?saved[key]:DEFAULT_SETTINGS[key];for(const [key,values] of [['enhancement',['natural','ocr','bw','original']],['provider',['camscanner','textin']]])$(key).value=values.includes(saved[key])?saved[key]:DEFAULT_SETTINGS[key];}
let uploadPreviewUrl=null;
function uploadPreview(file=null,current=job){if(uploadPreviewUrl){URL.revokeObjectURL(uploadPreviewUrl);uploadPreviewUrl=null}const src=file?(uploadPreviewUrl=URL.createObjectURL(file)):current?.original_url;const thumb=$('uploadThumb');thumb.hidden=!src;if(src)thumb.src=src;else thumb.removeAttribute('src');$('uploadIcon').hidden=!!src;$('uploadTitle').textContent=file?'图片已选择 · 点击下方上传':current?'图片已上传 · 点击可换图':'点击此处选择表格图片';$('fileName').textContent=file?`待上传 · ${file.name}`:current?`已上传 · ${current.name}`:'支持 JPG、PNG 等图片';}
$('file').onchange=()=>{const file=$('file').files[0];pendingFile=!!file;uploadPreview(file);guidance()};
$('nextAction').onclick=()=>{if(pendingFile)return $('uploadRecognize').click();if(!job)return $('file').click();if(job.status==='recognizing')return;if(job.cells.length){if(job.cells.every(c=>c.confirmed))return $('export').click();return $('startReview').click()}return $('recognize').click()};
let lastDeleted=null;
async function openHistory(id){if(!id)return;if(dirty&&!window.confirm('当前修改未保存，切换任务？'))return;clearTimeout(poll);adopt(await api(`/api/jobs/${id}`));if(job.status==='recognizing')watch();}
async function removeHistory(item){if(item.status==='recognizing')throw Error('识别中的任务暂不能删除');if(job?.id===item.id&&dirty&&!window.confirm('当前修改未保存，删除此历史记录？'))return;await api(`/api/jobs/${item.id}`,{method:'DELETE'});lastDeleted=item.id;$('undoDelete').hidden=false;if(job?.id===item.id){clearTimeout(poll);closeViewer();$('proof').close();job=null;$('exportName').value='';dirty=false;selected=null;pendingFile=false;try{localStorage.removeItem('lastJobId')}catch{}uploadPreview(null,null);$('imageWrap').hidden=true;document.querySelector('.empty').hidden=false;$('status').textContent='选择图片开始';$('count').textContent='';$('workflowHint').textContent='选择图片，开始新的任务';$('assessmentSummary').hidden=true;$('grid').innerHTML='';controls();guidance();}await history();toast('已移出历史记录，原图留档，可撤销删除');}
async function history(){const jobs=await api('/api/jobs');const names={prepared:'待识别',review:'待校对',recognizing:'识别中',failed:'失败'};$('history').innerHTML='<option value="">选择任务…</option>'+jobs.map(j=>`<option value="${j.id}">${esc(j.name)} · ${names[j.status]||esc(j.status)}</option>`).join('');if(job)$('history').value=job.id;$('historyCount').textContent=`（${jobs.length}）`;$('historyList').innerHTML=jobs.length?jobs.map(j=>`<div class="history-item ${job?.id===j.id?'current':''}"><button class="history-open" data-open="${j.id}"><strong>${esc(j.name)}</strong><small>${names[j.status]||esc(j.status)}</small></button><button class="history-delete" data-delete="${j.id}" ${j.status==='recognizing'?'disabled':''} aria-label="删除 ${esc(j.name)}">删除</button></div>`).join(''):'<p class="muted">暂无历史记录</p>';$('historyList').querySelectorAll('[data-open]').forEach(el=>el.onclick=()=>run(()=>openHistory(el.dataset.open)));$('historyList').querySelectorAll('[data-delete]').forEach(el=>el.onclick=()=>run(()=>removeHistory(jobs.find(j=>j.id===el.dataset.delete))));return jobs;}
$('undoDelete').onclick=()=>run(async()=>{if(!lastDeleted)return;await api(`/api/trash/${lastDeleted}/restore`,{method:'POST'});lastDeleted=null;$('undoDelete').hidden=true;await history();toast('已恢复历史记录')});

function adopt(j){if(binding)cancelSelection();if($('settingsDialog').open)$('settingsDialog').close();job=j;$('exportName').value='';try{localStorage.setItem('lastJobId',j.id);$('exportName').value=localStorage.getItem('exportName:'+j.id)||''}catch{}dirty=false;pendingFile=false;uploadPreview(null,j);selected=null;warping=false;binding=false;compare=false;closeViewer();mode='processed';render();image();history().catch(()=>{});}
function guidance(){
updateConfigNotice();

const working=job?.status==='recognizing',ready=job?.cells.length,failed=job?.status==='failed',done=ready&&job.cells.every(c=>c.confirmed);
let step=pendingFile||!job?1:working||!ready?2:done?4:3;
for(let i=1;i<=4;i++){const el=$('step'+i);el.classList.toggle('active',i===step);el.classList.toggle('complete',i<step)}
let title,help,action;
if(pendingFile){title='图片已选择，下一步开始识别';help='点击右侧按钮上传这张图片，完成增强、识别后自动进入图片校对。';action='上传并识别这张图片'}
else if(!job){title='第 1 步：选择一张表格照片';help='先选择图片；登录扫描全能王后，点击“上传并识别”。';action='选择图片'}
else if(working){title={enhance:'第 2 步：扫描全能王 AI 增强中',table:'第 2 步：扫描全能王表格识别中',assess:'正在本地定位格子与评估分数'}[job.phase]||'正在处理图片';help='请等待，完成后自动打开图片校对。';action='处理中，请等待'}
else if(failed){title='识别未完成，需要手动继续';help=job.error||'这次调用失败，原因未知。原图已保留。';action='继续识别当前图片'}
else if(done){title='第 4 步：全部格子已确认，可以导出';help='点击右侧导出可计算 Excel，第二张工作表会保留原图。';action='直接导出 Excel'}
else if(ready){title='第 3 步：点击图片上的格子，修改并确认';help='弹窗中看局部图 → 修改文字 → 点“确认此格 → 下一格”。可随时点“直接导出 Excel”，自动保存修改；未确认格子保留当前识别文字。';action='开始逐格校对'}
else{title='第 2 步：图片已上传，开始增强与识别';help='点击右侧按钮调用所选识别服务；完成后自动进入图片校对。';action='识别当前图片'}
$('nextTitle').textContent=title;$('nextHelp').textContent=help;$('nextAction').textContent=action;$('nextAction').disabled=busy||working;
$('next-step')?.classList.toggle('failed',failed);
}
function render(){if(!job){guidance();return;}const working=job.status==='recognizing',failed=job.status==='failed';
$('workflowHint').textContent=failed?'本次识别失败。原图已保留，详细原因见下方；可手动继续。':job.cells.length?`已识别 ${job.cells.length} 格。点击原图格子或“开始逐格校对”，看图修改与确认。`:working?'正在增强、识别或本地评估，完成后自动进入校对。':'图片已上传，尚未完成识别。点击“识别当前图片”继续。';
const names={prepared:'图片已上传',recognizing:'正在处理…',review:'等待图片校对',failed:'识别失败'};$('status').textContent=names[job.status]||job.status;$('count').textContent=`${job.cells.filter(c=>c.confirmed).length} / ${job.cells.length} 格已确认${dirty?' · 未保存':''}`;
$('warnings').textContent=[...job.warnings,job.error||''].filter(Boolean).join('\n');$('warnings').hidden=!$('warnings').textContent;$('warningDetails').hidden=!$('warnings').textContent;
$('assessmentSummary').hidden=!job.cells.length;$('assessmentSummary').textContent=`已评估 ${job.cells.filter(c=>c.candidate_score!=null).length} 格 · 低分或不一致 ${job.cells.filter(c=>color(c)==='red').length} 格 · 无分数 ${job.cells.filter(c=>score(c)===null).length} 格。分数为本地候选置信度，不代表正确率。`;
guidance();controls();filterControls();grid();overlay();}

function image(){if(!job)return;$('imageWrap').hidden=false;document.querySelector('.empty').hidden=true;$('image').src=mode==='original'?job.original_url:job.processed_url;$('before').src=job.original_url;$('before').hidden=!compare;$('sliderWrap').hidden=!compare;['original','processed'].forEach(id=>$(id).classList.toggle('active',mode===id));$('viewerOriginal').classList.toggle('active',mode==='original');$('viewerProcessed').classList.toggle('active',mode==='processed');$('viewerTitle').textContent=`${mode==='original'?'原图':'处理图'} · 大图校对`;}
function polygon(c){let p=c.polygon||[];if(p.length!==8)return [];if(mode==='original'){if(c.original_polygon?.length>=8)return c.original_polygon;if(!job.matrix)return [];const m=job.matrix; // Invert general 3x3 projective transform.
const [a,b,d]=m[0],[e,f,g]=m[1],[h,i,k]=m[2];const inv=[[f*k-g*i,d*i-b*k,b*g-d*f],[g*h-e*k,a*k-d*h,d*e-a*g],[e*i-f*h,b*h-a*i,a*f-b*e]];p=p.map((v,n)=>{const x=c.polygon[n-n%2],y=c.polygon[n-n%2+1],den=inv[2][0]*x+inv[2][1]*y+inv[2][2];return (inv[n%2][0]*x+inv[n%2][1]*y+inv[n%2][2])/den});}return p.every(Number.isFinite)?p:[];}
function overlay(){const img=$('image'),svg=$('overlay');if(!img.naturalWidth)return;svg.setAttribute('viewBox',`0 0 ${img.naturalWidth} ${img.naturalHeight}`);svg.replaceChildren();if(compare)return;for(const c of job.cells){const p=polygon(c);if(p.length<8)continue;const shape=document.createElementNS('http://www.w3.org/2000/svg','polygon');shape.setAttribute('points',p.reduce((s,v,n)=>s+(n%2?',':' ')+v,'').trim());const stroke={red:'#e04e67',yellow:'#c99d24',green:'#31966c',gray:'#96a3b4'}[color(c)];shape.setAttribute('stroke',stroke);shape.setAttribute('fill',stroke);const match=matchesFilter(c);shape.dataset.id=c.id;shape.dataset.match=String(match);if(filter!=='all'){shape.classList.add(match?'filter-match':'filter-muted');if(!match)shape.style.pointerEvents='none';if(match&&filter==='gray'){shape.setAttribute('stroke','#65748a');shape.setAttribute('fill','#65748a')}}if(c.id===selected)shape.classList.add('selected');const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=cellDetails(c);shape.append(title);shape.onclick=event=>{event.stopPropagation();if(warping||binding)return;if($('imageViewer').open)openCell(c.id);else openViewer()};svg.append(shape)}for(const p of points){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',p[0]);circle.setAttribute('cy',p[1]);circle.setAttribute('r',8);circle.setAttribute('fill','#2563eb');svg.append(circle)}}
function grid(){if(!job?.cells.length){$('grid').innerHTML='<p class=muted>识别完成后显示表格；也可手动补格校对。</p>';return;}const lookup=new Map(),cover=new Set();for(const c of job.cells){lookup.set(`${c.row},${c.col}`,c);for(let r=c.row;r<c.row+c.rowspan;r++)for(let col=c.col;col<c.col+c.colspan;col++)if(r!==c.row||col!==c.col)cover.add(`${r},${col}`)}const rows=Math.max(...job.cells.map(c=>c.row+c.rowspan-1)),cols=Math.max(...job.cells.map(c=>c.col+c.colspan-1));if(rows*cols>50000){$('grid').innerHTML='<p>表格过大，使用列表校对。</p>'+filtered().map(c=>`<button data-id="${esc(c.id)}">R${c.row} C${c.col}: ${esc(c.text)}</button>`).join('')}else{let html='<table>';for(let r=1;r<=rows;r++){html+='<tr>';for(let col=1;col<=cols;col++){const key=`${r},${col}`;if(cover.has(key))continue;const c=lookup.get(key);html+=c?`<td data-id="${esc(c.id)}" class="${color(c)} ${c.id===selected?'selected':''}" rowspan="${c.rowspan}" colspan="${c.colspan}" style="opacity:${filtered().includes(c)?1:.25}" title="${esc(cellDetails(c))}">${esc(c.text)}<small class="cell-score">${esc(scoreLabel(c))}</small></td>`:'<td title="缺失结构，使用补一个格子"></td>'}html+='</tr>'}html+='</table>';$('grid').innerHTML=html}$('grid').querySelectorAll('[data-id]').forEach(td=>td.onclick=()=>openCell(td.dataset.id));}
function openCell(id){const c=job.cells.find(c=>c.id===id);if(!c||!matchesFilter(c))return;selected=id;context=false;$('context').textContent='显示周围';for(const k of ['text','row','col','rowspan','colspan'])$(k).value=c[k];$('cellInfo').textContent=cellDetails(c);if(!$('proof').open)$('proof').showModal();crop();overlay();grid();}
function crop(){const c=job.cells.find(c=>c.id===selected),img=$('image'),can=$('crop');if(!c||!img.naturalWidth)return;const p=polygon(c);let x=0,y=0,w=img.naturalWidth,h=img.naturalHeight;if(p.length>=8){const xs=p.filter((_,n)=>n%2===0),ys=p.filter((_,n)=>n%2===1);x=Math.min(...xs);y=Math.min(...ys);w=Math.max(...xs)-x;h=Math.max(...ys)-y;const margin=context?Math.max(w*.3,h):8;x=Math.max(0,x-margin);y=Math.max(0,y-margin);w=Math.min(img.naturalWidth-x,w+margin*2);h=Math.min(img.naturalHeight-y,h+margin*2)}else $('cellInfo').textContent+=' · 无定位区域，显示整页；可手动框选绑定';const scale=Math.min(2,1200/Math.max(1,w));can.width=Math.max(1,Math.round(w*scale));can.height=Math.max(1,Math.round(h*scale));const ctx=can.getContext('2d');ctx.drawImage(img,x,y,w,h,0,0,can.width,can.height);if(p.length>=8){ctx.strokeStyle='#2563eb';ctx.lineWidth=2;ctx.beginPath();for(let n=0;n<p.length;n+=2){const px=(p[n]-x)*scale,py=(p[n+1]-y)*scale;n?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.stroke()}}
function edit(confirm=false){const c=job.cells.find(c=>c.id===selected);if(!c)return;const changed=['text','row','col','rowspan','colspan'].some(k=>String(c[k])!==$(k).value);for(const k of ['row','col','rowspan','colspan']){const n=Number($(k).value);if(!Number.isInteger(n)||n<1)throw Error('行列和跨度须是正整数');c[k]=n}c.text=$('text').value;if(changed)c.confirmed=false;if(confirm)c.confirmed=true;if(changed||confirm)dirty=true;render();}
async function save(){if($('proof').open)edit();const j=await api(`/api/jobs/${job.id}`,{method:'PUT',...body({revision:job.revision,cells:job.cells})});job=j;dirty=false;render();toast('已保存校对');}
async function advance(confirm){const list=filtered(),index=list.findIndex(c=>c.id===selected),next=list[index+1];edit(confirm);await save();if(next)openCell(next.id);else{$('proof').close();toast('当前筛选集合已校对到最后一项')}}
async function uploadJob(){if(!configurationReady&&!authLogged){openConfiguration();throw Error('请先确认配置，再上传识别')}const file=$('file').files[0];if(!file)throw Error('请先选择图片');if(dirty&&!window.confirm('当前校对尚未保存，继续上传？'))return;const data=new FormData();data.append('file',file);data.append('geometry',$('geometry').checked);data.append('enhancement',$('enhancement').value);adopt(await api('/api/jobs',{method:'POST',body:data}));return true;}
async function recognizeJob(){if(!job)return;if($('provider').value==='camscanner'||$('cloud').checked){const auth=await api('/api/auth/status');if(!auth.logged_in){openConfiguration();throw Error('请先在配置中登录扫描全能王，再开始识别。')}}job=await api(`/api/jobs/${job.id}/recognize`,{method:'POST',...body({provider:$('provider').value,app_id:$('appId').value,secret:$('secret').value,cloud_enhance:$('cloud').checked})});$('secret').value='';render();watch();}
$('assess').onclick=()=>run(async()=>{await save();job=await api(`/api/jobs/${job.id}/assess`,{method:'POST'});render();toast('正在本地定位与复核，不重复调用云端识别');watch()});$('upload').onclick=()=>run(uploadJob);$('uploadRecognize').onclick=()=>run(async()=>{if(await uploadJob())await recognizeJob()});$('recognize').onclick=()=>run(recognizeJob);$('startReview').onclick=()=>{const c=filtered().find(c=>!c.confirmed)||filtered()[0];if(c)openCell(c.id)};
function watch(){clearTimeout(poll);poll=setTimeout(async()=>{try{const j=await api(`/api/jobs/${job.id}`);job=j;render();if(j.status==='recognizing')watch();else{mode='processed';compare=false;image();history();if(j.status==='review'&&j.cells.length)openViewer()}}catch(e){toast(e.message)}},1000)}
function actionLabels(){const provider=$('provider').value==='camscanner'?'扫描全能王':'TextIn';$('uploadRecognize').textContent=`上传并用${provider}识别`;$('recognize').textContent=`${provider}${$('cloud').checked?'增强并':''}识别当前图`;$('keys').hidden=$('provider').value!=='textin'}$('provider').onchange=()=>{saveSettings();actionLabels()};$('cloud').onchange=()=>{saveSettings();actionLabels()};$('geometry').onchange=saveSettings;$('enhancement').onchange=saveSettings;
$('history').onchange=()=>run(()=>openHistory($('history').value));
for(const view of ['original','processed'])$(view).onclick=()=>{if(binding)cancelSelection();mode=view;compare=false;image()};
$('image').onload=()=>{overlay();if($('proof').open)crop()};
$('compare').onclick=()=>{if(!job)return;compare=!compare;mode='processed';image();overlay()};$('slider').oninput=()=>$('before').style.clipPath=`inset(0 ${100-$('slider').value}% 0 0)`;
let viewerPan={x:0,y:0},panGesture=null;
function applyViewerPan(){$('imageWrap').style.transform=$('imageViewer').open?`translate(${viewerPan.x}px,${viewerPan.y}px)`:'';}
function viewerScale(value,anchor=null){const next=Math.round(Math.max(25,Math.min(400,Number(value)))),previous=Number($('viewerScale').value)||100;const rect=$('imageWrap').getBoundingClientRect();if(anchor){const ratio=next/previous;viewerPan.x+=(anchor.x-rect.left)*(1-ratio);viewerPan.y+=(anchor.y-rect.top)*(1-ratio)}$('viewerScale').value=next;$('viewerScaleLabel').textContent=next+'%';$('imageWrap').style.width=$('imageViewer').open?Math.max(1,$('stage').clientWidth-28)*next/100+'px':'';applyViewerPan();}
function resetViewer(){viewerPan={x:0,y:0};viewerScale(100);$('stage').scrollTop=0;$('stage').scrollLeft=0;}
let guideCollapsed=false,guideRemembered=false;
try{guideRemembered=localStorage.getItem('reviewGuideCollapsed')==='true';guideCollapsed=guideRemembered}catch{}
function reviewGuide(){$('guideBody').hidden=guideCollapsed;$('guideRemember').checked=guideRemembered;$('guideToggle').textContent=guideCollapsed?'操作提示 · 展开':'操作提示 · 收起';$('guideToggle').setAttribute('aria-expanded',String(!guideCollapsed));}
$('guideToggle').onclick=()=>{guideCollapsed=!guideCollapsed;reviewGuide()};
$('guideRemember').onchange=()=>{guideRemembered=$('guideRemember').checked;guideCollapsed=guideRemembered;try{localStorage.setItem('reviewGuideCollapsed',String(guideRemembered))}catch{toast('浏览器未允许保存偏好，本次仍可收起提示')}reviewGuide()};
reviewGuide();
function openViewer(){if(!job||warping||binding)return;if(!$('imageViewer').open){$('viewerStage').append($('stage'));$('imageViewer').showModal();document.body.classList.add('viewer-open');resetViewer();}image();overlay();}
function closeViewer(){if(binding)cancelSelection();if($('imageViewer').open)$('imageViewer').close();$('stageHome').append($('stage'));$('imageWrap').style.width='';$('imageWrap').style.transform='';viewerPan={x:0,y:0};panGesture=null;$('stage').classList.remove('panning');document.body.classList.remove('viewer-open');}
$('imageViewer').addEventListener('close',closeViewer);
$('imageViewer').addEventListener('cancel',event=>{event.preventDefault();if(binding){cancelSelection();return;}closeViewer()});
$('closeViewer').onclick=closeViewer;$('zoom').onclick=openViewer;
$('viewerScale').oninput=()=>viewerScale($('viewerScale').value);$('viewerFit').onclick=resetViewer;
$('viewerOriginal').onclick=()=>{$('original').click()};$('viewerProcessed').onclick=()=>{$('processed').click()};
$('viewerExport').onclick=()=>run(()=>downloadExcel(false));
$('stage').onclick=()=>{if(!$('imageViewer').open&&!warping&&!binding)openViewer()};
$('stage').onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openViewer()}};
function selectFilter(f){if(binding)cancelSelection();if($('proof').open)edit();filter=filter===f&&f!=='all'?'all':f;if(!$('proof').open&&!matchesFilter(job?.cells.find(c=>c.id===selected)))selected=null;render();if($('proof').open&&!matchesFilter(job.cells.find(c=>c.id===selected))){const next=filtered()[0];if(next)openCell(next.id);else{selected=null;$('proof').close();overlay();toast('当前筛选没有对应格子')}}}
for(const f of ['red','yellow','gray','all'])for(const prefix of ['','viewer','proof']){const id=prefix?prefix+f[0].toUpperCase()+f.slice(1):f;if($(id))$(id).onclick=()=>selectFilter(f);}
$('stage').addEventListener('wheel',event=>{if(!$('imageViewer').open||$('proof').open||!event.deltaY)return;event.preventDefault();if(binding)return;const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?$('stage').clientHeight:1);viewerScale(Number($('viewerScale').value)*Math.exp(-Math.max(-300,Math.min(300,delta))*.0015),{x:event.clientX,y:event.clientY})},{passive:false});
$('stage').addEventListener('pointerdown',event=>{if(event.button!==1||!$('imageViewer').open)return;event.preventDefault();event.stopPropagation();panGesture={id:event.pointerId,x:event.clientX,y:event.clientY,panX:viewerPan.x,panY:viewerPan.y};$('stage').setPointerCapture(event.pointerId);$('stage').classList.add('panning')},true);
$('stage').addEventListener('pointermove',event=>{if(!panGesture||event.pointerId!==panGesture.id)return;event.preventDefault();viewerPan={x:panGesture.panX+event.clientX-panGesture.x,y:panGesture.panY+event.clientY-panGesture.y};applyViewerPan()});
function endPan(event){if(!panGesture||event.pointerId!==panGesture.id)return;const id=panGesture.id;panGesture=null;$('stage').classList.remove('panning');if($('stage').hasPointerCapture(id))$('stage').releasePointerCapture(id);}
for(const name of ['pointerup','pointercancel','lostpointercapture'])$('stage').addEventListener(name,endPan);
$('stage').addEventListener('auxclick',event=>{if(event.button===1&&$('imageViewer').open)event.preventDefault()});
window.addEventListener('resize',()=>{if($('imageViewer').open)viewerScale($('viewerScale').value)});
let autoConfirmClose=false;try{autoConfirmClose=localStorage.getItem('proofAutoConfirm')==='true'}catch{}
function autoConfirmControl(){$('autoConfirmSave').textContent=autoConfirmClose?'保存后变绿 ✓':'保存不标记';$('autoConfirmSave').classList.toggle('active',autoConfirmClose);$('autoConfirmSave').setAttribute('aria-pressed',String(autoConfirmClose));$('autoConfirmSave').title=autoConfirmClose?'点窗外保存时标记当前格为已校对':'点窗外只保存文字，不自动标记已校对';}
$('autoConfirmSave').onclick=()=>{autoConfirmClose=!autoConfirmClose;try{localStorage.setItem('proofAutoConfirm',String(autoConfirmClose))}catch{}autoConfirmControl()};autoConfirmControl();
async function saveProofAndClose(){if(!$('proof').open)return;edit();const c=job.cells.find(c=>c.id===selected),previous=c?.confirmed;if(autoConfirmClose&&c){c.confirmed=true;dirty=true;}try{await save();$('proof').close()}catch(e){if(c)c.confirmed=previous;render();throw e}}

$('closeProof').onclick=()=>run(saveProofAndClose);
let proofBackdropDown=false;
function outsideProof(event){const r=$('proof').getBoundingClientRect();return event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom;}
$('proof').addEventListener('pointerdown',event=>{proofBackdropDown=event.button===0&&event.target===$('proof')&&outsideProof(event)});
$('proof').addEventListener('click',event=>{const dismiss=proofBackdropDown&&event.target===$('proof')&&outsideProof(event);proofBackdropDown=false;if(dismiss){event.preventDefault();event.stopPropagation();run(saveProofAndClose)}});
$('proof').addEventListener('cancel',e=>{e.preventDefault();$('closeProof').click()});
$('proofOriginal').onclick=()=>{mode='original';compare=false;image()};$('proofProcessed').onclick=()=>{mode='processed';compare=false;image()};
$('context').onclick=()=>{context=!context;$('context').textContent=context?'仅看此格':'显示周围';crop()};
$('save').onclick=()=>run(save);$('next').onclick=()=>run(()=>advance(false));$('confirmNext').onclick=()=>run(()=>advance(true));
function exportFilename(){let name=$('exportName').value.trim().replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/g,'').replace(/\.xlsx$/i,'').replace(/[. ]+$/g,'');if(/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(name))name='_'+name;return (name||`表格-${job.id.slice(0,8)}`)+'.xlsx';}
$('exportName').oninput=()=>{if(job)try{localStorage.setItem('exportName:'+job.id,$('exportName').value)}catch{}};
async function downloadExcel(draft=false){await save();const response=await fetch(`/api/jobs/${job.id}/excel${draft?'?draft=true':''}`);if(!response.ok){const e=await response.json();throw Error(e.detail)}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=exportFilename();link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('export').onclick=()=>run(()=>downloadExcel(false));$('exportDraft').onclick=()=>run(()=>downloadExcel(true));$('proofExport').onclick=()=>run(()=>downloadExcel(false));
$('deleteCell').onclick=()=>{if(!window.confirm('删除当前格子？不会删除原图。'))return;job.cells=job.cells.filter(c=>c.id!==selected);dirty=true;selected=null;$('proof').close();render()};
$('warp').onclick=()=>{if(!job)return;warping=true;points=[];compare=false;mode='original';image();toast('在原图依次点击：左上、右上、右下、左下')};
function at(event){const rect=$('image').getBoundingClientRect();return [(event.clientX-rect.left)*$('image').naturalWidth/rect.width,(event.clientY-rect.top)*$('image').naturalHeight/rect.height]}
$('imageWrap').onclick=event=>{if(warping){points.push(at(event));overlay();if(points.length===4){warping=false;run(async()=>{job=await api(`/api/jobs/${job.id}/warp`,{method:'POST',...body({points})});points=[];mode='processed';image();render();toast('手动透视拉正完成')})}}};
let selectionKind='existing',selectionPointer=null;
function selectionMode(active){binding=active;$('imageWrap').classList.toggle('selecting',active);$('stage').classList.toggle('selecting',active);$('selectionHint').hidden=!active;$('viewerSelect').classList.toggle('active',active);$('viewerSelect').textContent=active?'▣ 退出框选':'▣ 框选补格';$('viewerSelect').setAttribute('aria-pressed',String(active));}
function cancelSelection(){const pointer=selectionPointer;dragStart=null;selectionPointer=null;$('selectionRect').hidden=true;selectionMode(false);if(pointer!==null&&$('imageWrap').hasPointerCapture(pointer))$('imageWrap').releasePointerCapture(pointer);}
function startSelection(kind){if(!job||busy||job.status==='recognizing')return;if(binding){cancelSelection();return;}if(kind==='existing'){edit();$('proof').close();}openViewer();selectionKind=kind;compare=false;mode='processed';image();selectionMode(true);$('overlay').hidden=false;toast('按右键或者 Esc 可以退出框选');}
$('viewerSelect').onclick=()=>startSelection('new');
$('bind').onclick=()=>startSelection('existing');
$('imageWrap').style.touchAction='none';
function selectionBounds(event){const end=at(event),w=$('image').naturalWidth,h=$('image').naturalHeight;return {x:Math.max(0,Math.min(w,dragStart[0],end[0])),y:Math.max(0,Math.min(h,dragStart[1],end[1])),xx:Math.max(0,Math.min(w,Math.max(dragStart[0],end[0]))),yy:Math.max(0,Math.min(h,Math.max(dragStart[1],end[1])))};}
function drawSelection(event){const box=selectionBounds(event),rect=$('selectionRect'),img=$('image');rect.hidden=false;rect.style.left=box.x/img.naturalWidth*100+'%';rect.style.top=box.y/img.naturalHeight*100+'%';rect.style.width=(box.xx-box.x)/img.naturalWidth*100+'%';rect.style.height=(box.yy-box.y)/img.naturalHeight*100+'%';return box;}
$('imageWrap').onpointerdown=event=>{if(binding&&event.button===0){event.preventDefault();event.stopPropagation();dragStart=at(event);selectionPointer=event.pointerId;$('imageWrap').setPointerCapture(event.pointerId);drawSelection(event)}};
$('imageWrap').onpointermove=event=>{if(binding&&dragStart&&event.pointerId===selectionPointer){event.preventDefault();drawSelection(event)}};
$('imageWrap').onpointerup=event=>{if(!binding||!dragStart||event.pointerId!==selectionPointer||event.button!==0)return;event.preventDefault();event.stopPropagation();const {x,y,xx,yy}=drawSelection(event);if(xx-x<2||yy-y<2){const pointer=selectionPointer;dragStart=null;selectionPointer=null;$('selectionRect').hidden=true;if($('imageWrap').hasPointerCapture(pointer))$('imageWrap').releasePointerCapture(pointer);toast('区域太小，请重新拖动');return;}let c=selectionKind==='existing'?job.cells.find(c=>c.id===selected):null;
if(selectionKind==='new'){const cx=(x+xx)/2,cy=(y+yy)/2;c=job.cells.find(c=>{const p=c.polygon||[];if(p.length!==8||c.text.trim())return false;const xs=p.filter((_,n)=>n%2===0),ys=p.filter((_,n)=>n%2===1);return cx>=Math.min(...xs)&&cx<=Math.max(...xs)&&cy>=Math.min(...ys)&&cy<=Math.max(...ys)});if(!c){c={id:crypto.randomUUID(),row:Math.max(0,...job.cells.map(c=>c.row+c.rowspan-1))+1,col:1,rowspan:1,colspan:1,text:'',score:null,polygon:[],confirmed:false,kind:'cell'};job.cells.push(c);$('proof').querySelector('.structure-settings').open=true;toast('已添加补格，请填写文字并核对行列位置');}}
if(c){c.polygon=[x,y,xx,y,xx,yy,x,yy];c.original_polygon=[];c.confirmed=false;dirty=true;cancelSelection();if(!matchesFilter(c))filter='all';render();openCell(c.id);$('text').focus();}else cancelSelection();};
$('imageWrap').addEventListener('pointercancel',()=>{if(binding)cancelSelection()});
$('imageWrap').addEventListener('lostpointercapture',()=>{if(binding&&dragStart)cancelSelection()});
$('stage').addEventListener('contextmenu',event=>{if(binding){event.preventDefault();event.stopPropagation();cancelSelection();toast('已退出框选')}});
$('imageViewer').addEventListener('contextmenu',event=>{if(binding){event.preventDefault();cancelSelection();toast('已退出框选')}});
window.addEventListener('keydown',event=>{if(binding&&event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();cancelSelection();toast('已退出框选')}},true);
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
let authPoll=null,loginBusy=false,authWindow=null;
function displayAuth(state){authChecked=true;authLogged=state.logged_in===true;updateConfigNotice();const waiting=state.login_in_progress&&!state.logged_in;const link=state.login_url;$('authLink').hidden=!waiting||!link;if(waiting&&link){$('authLink').href=link;if(authWindow){try{authWindow.location.href=link}catch{}authWindow=null}}$('cancelLogin').hidden=!waiting;$('authState').textContent=state.logged_in?'已登录扫描全能王':state.login_error|| (waiting?(link?'请点击下方授权链接，在官方页面登录（有效期约5分钟）。':'正在获取官方授权链接…'):state.message||'请点击登录');$('login').textContent=state.logged_in?'已登录扫描全能王':waiting?'等待授权…':'登录扫描全能王';$('login').disabled=loginBusy||state.logged_in||waiting;return waiting;}
async function refreshAuth(){clearTimeout(authPoll);try{const state=await api('/api/auth/status');if(displayAuth(state))authPoll=setTimeout(refreshAuth,1500)}catch(e){authChecked=true;authLogged=false;updateConfigNotice();$('authState').textContent='登录状态检查失败，请刷新重试';$('login').disabled=loginBusy}}
$('login').onclick=async()=>{if(loginBusy)return;loginBusy=true;$('login').disabled=true;$('authState').textContent='正在获取官方授权链接…';try{authWindow=window.open('about:blank','_blank');const state=await api('/api/auth/login',{method:'POST'});displayAuth(state);toast(state.message)}catch(e){if(authWindow){try{authWindow.close()}catch{}authWindow=null}toast(e.message)}finally{loginBusy=false;refreshAuth()}};
$('cancelLogin').onclick=async()=>{try{await api('/api/auth/cancel',{method:'POST'});await refreshAuth()}catch(e){toast(e.message)}};
$('refreshAuth').onclick=refreshAuth;
restoreSettings();actionLabels();history().then(jobs=>{let last;try{last=localStorage.getItem('lastJobId')}catch{}const j=jobs.find(j=>j.id===last)||jobs[0];if(j){adopt(j);if(j.status==='recognizing')watch()}}).catch(e=>toast(e.message));controls();guidance();refreshAuth();
